const $=id=>document.getElementById(id);
const mapSvg=$('mapSvg'), mapImage=$('mapImage'), markerLayer=$('markerLayer'), search=$('search'), seaList=$('seaList');
let activeRegion=(location.hash||'#europe').slice(1); if(!REGIONS[activeRegion]) activeRegion='europe';
let mode='study'; let studyFilter=null; let lastGameMode='game10';
let game={running:false,pool:[],i:0,target:null,wrongThis:0,score:0,mistakes:0,completed:0,locked:false,wrongIds:new Set(),doneIds:new Set(),missedIds:new Set()};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s){return s.toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function currentIds(quiz=false){let ids=quiz?REGIONS[activeRegion].quizIds:REGIONS[activeRegion].ids; if(mode==='study'&&studyFilter) ids=ids.filter(id=>studyFilter.has(id)); return ids}
function renderRegions(){const g=$('regionGrid');g.innerHTML='';REGION_ORDER.forEach(k=>{const b=document.createElement('button');b.className='regionBtn'+(k===activeRegion?' active':'')+(k==='world'?' world':'');b.textContent=REGIONS[k].label;b.onclick=()=>switchRegion(k);g.appendChild(b)})}
function switchRegion(k){if(k===activeRegion)return;if(game.running)game.running=false;activeRegion=k;location.hash=k;studyFilter=null;$('questionCard').classList.remove('show');$('endCard').classList.remove('show');$('startCard').classList.toggle('show',mode!=='study');game.doneIds=new Set();game.missedIds=new Set();renderRegions();renderMap();syncPanel();}
function svgEl(tag,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e}
function renderMap(){const R=REGIONS[activeRegion];mapImage.setAttributeNS('http://www.w3.org/1999/xlink','href','data:image/png;base64,'+REGION_IMAGES[activeRegion]);markerLayer.innerHTML='';
 const ids=currentIds(false); for(const id of ids){const p=R.positions[id]; if(!p)continue; const s=SEAS[id]; const g=svgEl('g',{class:'markerG','data-id':id}); const hit=svgEl('circle',{class:'markerHit',cx:p[0],cy:p[1],r:24}); const dot=svgEl('circle',{class:'markerDot',cx:p[0],cy:p[1],r:7}); g.append(hit,dot); g.addEventListener('click',()=>onMarker(id)); markerLayer.appendChild(g);
  const lab=R.labels[id]; if(lab){const [tx,ty,anchor]=lab; const lg=svgEl('g',{class:'studyLabel','data-id':id}); const endX=tx+(anchor==='start'?-8:8); const line=svgEl('line',{x1:p[0],y1:p[1],x2:endX,y2:ty}); const text=svgEl('text',{x:tx,y:ty+6,'text-anchor':anchor}); text.textContent=s.name; lg.append(line,text); markerLayer.appendChild(lg)} }
 syncMarkerStates(); renderList(); }
function syncMarkerStates(){markerLayer.querySelectorAll('.markerG').forEach(g=>{const id=g.dataset.id;g.classList.toggle('done',game.doneIds.has(id));g.classList.toggle('missed',game.missedIds.has(id))})}
function renderList(){if(mode!=='study')return;const q=norm(search.value||'');seaList.innerHTML='';currentIds(false).filter(id=>{const s=SEAS[id];return !q||norm([s.name,...(s.aliases||[])].join(' ')).includes(q)}).sort((a,b)=>SEAS[a].name.localeCompare(SEAS[b].name,'pl')).forEach(id=>{const s=SEAS[id],b=document.createElement('button');b.className='seaItem'+(studyFilter?' filtered':'');b.innerHTML=`<span class="seaDot"></span><span>${esc(s.name)}</span>`;b.onmouseenter=()=>highlight(id,true);b.onmouseleave=()=>highlight(id,false);b.onclick=()=>pulseLabel(id);seaList.appendChild(b)})}
function highlight(id,on){const g=markerLayer.querySelector(`.markerG[data-id="${id}"]`);if(g){const dot=g.querySelector('.markerDot');if(dot)dot.setAttribute('r',on?11:7)}const l=markerLayer.querySelector(`.studyLabel[data-id="${id}"] text`);if(l)l.setAttribute('fill',on?'#0f5fd7':'#17324d')}
function pulseLabel(id){highlight(id,true);setTimeout(()=>highlight(id,false),900)}
function setMode(m){mode=m; if(m!=='study')lastGameMode=m; document.body.classList.toggle('study-mode',m==='study');document.body.classList.toggle('quiz-mode',m!=='study');document.querySelectorAll('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('studyBlock').style.display=m==='study'?'flex':'none';$('questionCard').classList.remove('show');$('endCard').classList.remove('show');$('startCard').classList.toggle('show',m!=='study');game.running=false;game.doneIds=new Set();game.missedIds=new Set();syncPanel();renderMap()}
function syncPanel(){const R=REGIONS[activeRegion];$('mapTitle').textContent=R.label;$('mapNote').textContent=R.note;if(mode==='study'){$('studyTitle').textContent=studyFilter?'Ściągawka • tylko błędne':'Ściągawka';$('studyText').textContent=studyFilter?`Pokazuję ${studyFilter.size} pozycji, z którymi był problem.`:'Wszystkie kółka mają od razu kreseczkę i nazwę morza.'} else {const n=mode==='game10'?Math.min(10,R.quizIds.length):R.quizIds.length;$('startTitle').textContent=mode==='game10'?'Gra • 10':'Pełna gra';$('startText').textContent=`Kliknij „Graj”. W tej rundzie: ${n} ${n===1?'morze':'mórz'}.`}}
function onMarker(id){if(mode==='study'){pulseLabel(id);return}if(!game.running||game.locked||!game.target)return;if(game.doneIds.has(id))return;if(id===game.target){const pts=game.wrongThis===0?10:5;game.score+=pts;game.completed++;game.locked=true;game.doneIds.add(id);feedbackGood(`Dobrze — ${SEAS[id].name}. +${pts} pkt.`);syncMarkerStates();updateGameUI();setTimeout(nextQuestion,650);return}
 game.mistakes++;game.wrongThis++;game.wrongIds.add(game.target);flashWrong(id);if(game.wrongThis===1){feedbackBad('Źle. Masz jeszcze jedną próbę.');updateGameUI();return}game.completed++;game.locked=true;game.missedIds.add(game.target);feedbackReveal(`To było: ${SEAS[game.target].name}.`);revealCorrect(game.target);syncMarkerStates();updateGameUI();setTimeout(nextQuestion,1500)}
function flashWrong(id){const g=markerLayer.querySelector(`.markerG[data-id="${id}"]`);if(!g)return;g.classList.add('flashWrong');setTimeout(()=>g.classList.remove('flashWrong'),420)}
function feedbackGood(t){$('feedback').className='feedback good';$('feedback').textContent=t}function feedbackBad(t){$('feedback').className='feedback bad';$('feedback').textContent=t}function feedbackReveal(t){$('feedback').className='feedback reveal';$('feedback').textContent=t}
function revealCorrect(id){const p=REGIONS[activeRegion].positions[id];if(!p)return;const r=svgEl('circle',{class:'answerRing',cx:p[0],cy:p[1],r:82});markerLayer.appendChild(r);setTimeout(()=>r.remove(),1250)}
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function startGame(customIds=null){if(mode==='study'){setMode(lastGameMode)}const all=customIds||REGIONS[activeRegion].quizIds;const n=mode==='game10'?Math.min(10,all.length):all.length;game={running:true,pool:shuffled(all).slice(0,n),i:0,target:null,wrongThis:0,score:0,mistakes:0,completed:0,locked:false,wrongIds:new Set(),doneIds:new Set(),missedIds:new Set()};$('startCard').classList.remove('show');$('endCard').classList.remove('show');$('questionCard').classList.add('show');renderMap();nextQuestion()}
function nextQuestion(){if(!game.running)return;if(game.i>=game.pool.length){finishGame(false);return}game.target=game.pool[game.i++];game.wrongThis=0;game.locked=false;$('questionName').textContent=SEAS[game.target].name;$('feedback').className='feedback';$('feedback').textContent='Kliknij właściwe kółko.';updateGameUI()}
function updateGameUI(){const total=game.pool.length;$('roundLabel').textContent=`Pytanie ${Math.min(game.i,total)} z ${total}`;$('scoreStat').textContent=game.score;$('mistakeStat').textContent=game.mistakes;$('leftStat').textContent=Math.max(0,total-game.completed);$('progressBar').style.width=(total?game.completed/total*100:0)+'%'}
function skip(){if(!game.running||game.locked||!game.target)return;game.completed++;game.locked=true;game.wrongIds.add(game.target);game.missedIds.add(game.target);feedbackReveal(`Pominięto: ${SEAS[game.target].name}.`);revealCorrect(game.target);syncMarkerStates();updateGameUI();setTimeout(nextQuestion,1400)}
function finishGame(early=false){if(!game.pool.length)return;const total=game.pool.length,max=total*10,pct=max?Math.round(game.score/max*100):0;game.running=false;game.locked=true;$('questionCard').classList.remove('show');$('startCard').classList.remove('show');$('endCard').classList.add('show');$('endTitle').textContent=early?'Gra zakończona':'Runda ukończona';$('endScore').textContent=`${game.score} / ${max} pkt`;$('endText').textContent=`Ukończono ${game.completed} z ${total}. Błędne kliknięcia: ${game.mistakes}. Do powtórki: ${game.wrongIds.size}. Wynik: ${pct}%.`;}
function learnWrong(){studyFilter=new Set(game.wrongIds);mode='study';document.body.className='study-mode';document.querySelectorAll('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode==='study'));$('studyBlock').style.display='flex';$('endCard').classList.remove('show');$('startCard').classList.remove('show');$('questionCard').classList.remove('show');game.running=false;syncPanel();renderMap()}
function learnAll(){studyFilter=null;mode='study';document.body.className='study-mode';document.querySelectorAll('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode==='study'));$('studyBlock').style.display='flex';$('endCard').classList.remove('show');$('startCard').classList.remove('show');$('questionCard').classList.remove('show');game.running=false;syncPanel();renderMap()}
function init(){renderRegions();renderMap();syncPanel();document.querySelectorAll('.modeBtn').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('playBtn').onclick=()=>startGame();$('skipBtn').onclick=skip;$('endBtn').onclick=()=>finishGame(true);$('learnWrongBtn').onclick=learnWrong;$('learnAllBtn').onclick=learnAll;$('againBtn').onclick=()=>{setMode(lastGameMode);startGame()};search.oninput=renderList;document.addEventListener('selectstart',e=>{if(e.target!==search)e.preventDefault()});window.addEventListener('hashchange',()=>{const k=location.hash.slice(1);if(REGIONS[k]&&k!==activeRegion)switchRegion(k)});}
init();
